A pull request on Awesome Books
dlwub/Awesome-Books pull request #2
Opened 2022-08-09 17:28 UTC by dlwub

We did the following things to implement the Awesome Books page:
- We created a collection that keeps a list of books
- We created a function to add a new book to the collection, with title and author, a function to remove a book from the collection, and a function to display all books saved in the collection in the top part of the page.
- When a user clicks the "Add" button, a new book is added to the collection and the new book is displayed on the page.
- When a user clicks the "Remove" button, the correct book is removed from the collection and the book disappears from the page.
- The data is preserved in the browser's memory by using and retrieved when the page reloads.

2022-08-09 17:47 UTC, vechicin requested changes
# Hi @dlwub and @kusiLaw ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good job implementing all of the features required for this milestone!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-09 17:47 UTC, vechicin commented on index.js
> +});
[OPTIONAL] Consider emptying the input fields after form submission, it'll make for better UI/UX.

2022-08-09 17:47 UTC, vechicin commented on index.js
> +  // booksArray = booksArray.filter((book) => book.title !== title);
Please remove this commented line to keep a cleaner codebase.

2022-08-09 17:47 UTC, vechicin commented on index.js
> +  // addToPage(title, author)
Please remove this commented line to keep a cleaner codebase.

2022-08-09 17:47 UTC, vechicin commented on index.html
> +          <input id="author-input" type="text" placeholder="Auuthor" name="author"><br/><br/>
[OPTIONAL] Consider changing the placeholder to `Author` to make for better UI/UX.

2022-08-09 17:47 UTC, vechicin commented on index.js
> +      booksArray.push(book);
[OPTIONAL] Consider using methods that don't mutate the array.

<img width="961" alt="Screen Shot 2022-08-09 at 12 44 05" src="https://user-images.githubusercontent.com/82426682/183723299-132fef67-9c45-4313-9e12-612ea5cec25d.png">

2022-08-09 17:47 UTC, vechicin commented on index.js
> +    booksArray.splice(loc[1], 1);
[OPTIONAL] Consider using methods that don't mutate the array.

<img width="961" alt="Screen Shot 2022-08-09 at 12 45 05" src="https://user-images.githubusercontent.com/82426682/183723455-81aae546-cda3-48ac-a320-1cea9185e480.png">

2022-08-09 17:47 UTC, vechicin commented on index.js
> +      };
[OPTIONAL] Consider giving books a unique `id`.

<img width="856" alt="Screen Shot 2022-08-09 at 12 46 10" src="https://user-images.githubusercontent.com/82426682/183723649-f709fe8c-b080-4592-9951-89a3362815b4.png">

2022-08-10 09:05 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @dlwub ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

- [ ] Kindly make sure your readme file is well formatted. Please remove the second author and make sure the correct Github handle is added.

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-10 09:08 UTC, merged